#ArcSight Properties File
#Format Preserving Encryption Enabled Flag should NOT be manually edited! 
#Mon Mar 23 10:52:18 IST 2026
agents.maxAgents=1

agents[0].AgentSequenceNumber=0
agents[0].aggregationcachesize=1000
agents[0].connector.group.name=
agents[0].customsubagentlist=EfficientIP1_syslog|ciscopix_syslog|netscreen_syslog|cyberguard_syslog|niksun_syslog|sourcefire_syslog|intrushield_syslog|ciscovpnios_syslog|sonicwall_syslog|apache_syslog|netscreen_idp_syslog
|ciscovpnnoios_syslog|attackmitigator_syslog|rsaace_syslog|ciscoaironet_syslog|ciscoworks_syslog|ciscorouter_syslog|nortelvpn_syslog|pf_syslog|coreguard_syslog|watchguard_syslog|fortigate_syslog|peakflow_syslog|
honeyd_syslog|neoteris_syslog|prosafe_syslog|trushield_syslog|alcatel_syslog|extreme_syslog|tippingpoint_syslog|nokiasecurityplatform_syslog|whatsup_syslog|airdefense_syslog|stealthwatch_syslog|nagios_syslog|
netcontinuum_syslog|cef_syslog|tlattackmitigator_ng_syslog|airmagnet_enterprise_syslog|manhunt_syslog|m40e_aspic_syslog|ironmail_syslog|ciscorouter_nonios_syslog|ingrian_syslog|nitrosecurity_syslog|
junipernetscreenvpn_syslog|catos_syslog|ipolicy_syslog|symantecnetworksecurity_syslog|bigiron_syslog|type80_syslog|miragecounterpoint_syslog|newbury_syslog|packetalarm_syslog|cyberguard6_syslog|neowatcher_syslog|
netkeeper_syslog|snare_syslog|ntsyslog_syslog|f5bigip_syslog|sms_syslog|ciscocss_syslog|barracuda_spamfw_syslog|radware_defensepro_syslog|barracuda_spamfw_ng_syslog|bluecoatsg_syslog|peakflowx_syslog|aruba_syslog|
mcafeesig_syslog|stonegate_syslog|ciscosecureacs_syslog|tripwire_enterprise_7_7_syslog|tripwire_enterprise_syslog|datagram_iis_syslog|oracle_audit_syslog|sms7x_syslog|messagegate_syslog|cyberguard52_syslog|
symantecendpointprotection_syslog|cisco_mse|junipernetscreenvpn_6x_syslog|netscreen_idp5_syslog|bsm_syslog|junipernetscreenvpn_keyvalue_syslog|citrix_syslog|linux_auditd_syslog|netappfiler_syslog|vmwareesx_syslog|
ciscoise_monitoringaudit_syslog|ciscoairspace76_syslog|junos_sdsyslog|type80v3_syslog|vormetricdatasecurity_syslog|citrixnetscaler_syslog|tippingpoint_sms_2_5_syslog|tippingpoint_sms_audit_syslog|
tippingpoint_device_audit_syslog|vmwareesx_4_1_syslog|aixaudit_syslog|infobloxnios_syslog|proofpoint_syslog|ciscomeraki_syslog|junos_syslog|cisco_nxos_syslog|ciscoise_syslog|hpprinter_syslog|hp_c7000_syslog|
pulseconnectsecure_syslog|pulsepolicysecure_syslog|pulseconnectsecure_keyvalue_syslog|snare_syslog_heartbeat|ilo_syslog|ironport_websecurity_syslog|ironport_syslog|sidewinder_syslog|gauntlet_syslog|
flexagent_syslog|sendmail_syslog|nsm_syslog|nsm2009_syslog|ciscosecureacs51_syslog|hph3c_syslog|hp_ux_syslog|checkpoint_syslog|hpprocurve_syslog|mcafee_webgateway_syslog|isamaudit|isamsystem|barracuda_ng_firewall_f|
barracuda_ng_firewall_f_streaming|checkpoint_extra_syslog|arborsecurity_syslog|generic_syslog|ciscoairspace_syslog|proofpointTAPv2_syslog
agents[0].destination.count=1
agents[0].destination[0].agentid=3YY1rNpcBABCLTFhoQ1nydQ\=\=
agents[0].destination[0].failover.count=1
agents[0].destination[0].failover[0].agentid=3TAQht4oBABCACW6exxOV5w\=\=
agents[0].destination[0].failover[0].params=<?xml version\="1.0" encoding\="UTF-8"?>\n<ParameterValues>\n    <Parameter Name\="cefver" Value\="0.1"/>\n    <Parameter Name\="port" Value\="443"/>\n    <Parameter Name\="host" Value\="172.16.223.111"/>\n    <Parameter Name\="rcvrname" Value\="DNS_DDI_51417_FO"/>\n    <Parameter Name\="compression" Value\="Disabled"/>\n</ParameterValues>\n
agents[0].destination[0].failover[0].type=loggersecure
agents[0].destination[0].params=<?xml version\="1.0" encoding\="UTF-8"?>\n<ParameterValues>\n    <Parameter Name\="host" Value\=""/>\n    <Parameter Name\="port" Value\="443"/>\n    <Parameter Name\="rcvrname" Value\="DNS_DDI_51419"/>\n    <Parameter Name\="compression" Value\="Enabled"/>\n    <Parameter Name\="cefver" Value\="0.1"/>\n    <Parameter Name\="fipsciphers" Value\="fipsDefault"/>\n</ParameterValues>\n
agents[0].destination[0].type=loggersecure
agents[0].deviceconnectionalertinterval=60000
agents[0].enabled=true
agents[0].encoding=UTF-8
agents[0].entityid=7uAdt4oBABCABoyvKcZI6A\=\=
agents[0].fcp.version=0
agents[0].filequeuemaxfilecount=100
agents[0].filequeuemaxfilesize=10000000
agents[0].forwarder=false
agents[0].forwardmode=false
agents[0].id=3YY1rNpcBABCLTFhoQ1nydQ\=\=
agents[0].ipaddress=(ALL)
agents[0].overwriterawevent=false


agents[0].persistenceinterval=0
agents[0].port=51419
agents[0].protocol=UDP
agents[0].rawloginterval=-1
agents[0].rawlogmaxsize=-1
agents[0].syslog.subagent.parsers=



agents[0].tcpbindretrytime=5000
agents[0].tcpbuffersize=10240
agents[0].tcpcleanupdelay=-1
agents[0].tcpmaxbuffersize=1048576
agents[0].tcpmaxidletime=-1
agents[0].tcpmaxsockets=1000
agents[0].type=syslog


agents[0].unparsedevents.log.enabled=false
agents[0].usecustomsubagentlist=false
agents[0].usefilequeue=true
loggersecure.transport.ssl.certs.checked=Sat Mar 16 11\:19\:23 IST 2024
remote.management.enabled=true
remote.management.listener.port=9013
remote.management.second.listener.port=10001
remote.management.ssl.key.password.encrypted=OBFUSCATE.4.9.0\:OsI22VMFwPIqMsLukkhkkjWXc1ETgMDGRs9huKx7Gj+zkga0
remote.management.ssl.keystore.password.encrypted=OBFUSCATE.4.9.0\:HZFUcEu5Q1sMrheUDCimVAwIgQzoJsK7MC2NK7YaaS3eutrt
remote.management.ssl.organizational.unit=iMEat4oBABCAAYyvKcZI6A
ssl.fips.keystore.password.encrypted=OBFUSCATE.4.9.0\:Jm2XeZigknHuQLDrK1kf1TbFwyqhkIo+VPa6twNsEHSq9A0E
ssl.fips.truststore.password.encrypted=OBFUSCATE.4.9.0\:dB2nPclnTJBbcdg0fJoKZRgEmA9bUR8Fnc6wbLohGahLnnPj
ssl.keystore.password.encrypted=OBFUSCATE.4.9.0\:RuTtRgjblGG0hvfwtQVFT4CFAKbosblY1uEeGbU/+wj6B63y
ssl.truststore.password.encrypted=OBFUSCATE.4.9.0\:ZkxcPWCTDbigroEZiQ4/8gSHl6FPwxur44Xo8221XVG2kwOQ
syslogng.tls.key.password.encrypted=OBFUSCATE.4.9.0\:z5djzSbnaJl9JKYUP2fljbQ8DmkqBSAMLqnLV0J3/TzsBYNL
syslogng.tls.keystore.password.encrypted=OBFUSCATE.4.9.0\:afIcgHBfwFZAAmvVx9IaWS4XzNuqSGeawC+hnTQ7F6F2pJoe
